### ISSUE TITLE
Can RTTY decoding be improved ?

### ISSUE THREAD

**Issue by zanco** [projecthorus/horus-gui#21]
[delta8-r rtty.zip](https://github.com/projecthorus/horus-gui/files/7128526/delta8-r.rtty.zip)

The RTTY decoder, both tested with 200 baud and now with 100 baud (Stuart Robinson firmware) decodes not as good as dl-fldigi does. 

The mask estimation and the tuning into the spectrum would be pro's for running rtty decoding on horus-gui :-)

Is there room for improvement ? I attached a wav file (zip format) with 2 strings recorded from the IC-
[delta8-r rtty.zip](https://github.com/projecthorus/horus-gui/files/7128524/delta8-r.rtty.zip)
9700 output 

Thanks
Ben

**Comment by darksidelemm** [comment]
The short answer here is 'No. Improve your transmitter code.'

The FSK modem that underlies horus-gui and horusdemodlib performs within ~0.3dB of FSK demodulator theory: https://github.com/drowe67/codec2/blob/master/README_fsk.md
There is no room for improvement, apart from perhaps going to a coherent FSK demodulator, but that then places additional requirements on the transmitter.

HOWEVER - As I state on the main horus-gui page ( https://github.com/projecthorus/horus-gui#important-performance-notes ) the modem is a FSK modem. It expects the transmitter to behave like one too. This means:
- Have a symbol rate which is close to the desired symbol rate (within +/- 1000 ppm).
- Maintain that symbol rate throughout a transmission (i.e. not drift in symbol rate across a transmission)
- Not have gaps between transmitted bytes.

This is the trade-off. To get weak signal performance your transmitter needs to be good too.

I suspect the third point is the issue here. Looking at the code I suspect that there are significant gaps between transmitted bytes. Compare with the RS41HUP code, where modulation is performed in an interrupt, and doesn't seem to have these kinds of issues (in either 4FSK mode or RTTY).

My suggestion would be to switch to an interrupt-based transmission system.

**Comment by darksidelemm** [comment]
I've pointed out the issue in the RadioLib RTTY library here: https://github.com/jgromes/RadioLib/issues/306#issuecomment-915177878
